(autoload 'tinydesk-verbose                     "tinydesk" "" t 'macro)
(autoload 'tinydesk-nconc                       "tinydesk" "" nil 'macro)
(autoload 'tinydesk-pmin                        "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-string-match                "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-file-name-remote-p          "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-kill-line                   "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-string-match-case           "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-file-mode-make-writable     "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-remove-whitespace-eol       "tinydesk" "" nil)
(autoload 'tinydesk-install-default-keybindings "tinydesk" "" t)
(autoload 'tinydesk-default-mode-bindings       "tinydesk" "" nil)
(autoload 'tinydesk-comment                     "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-comment-re                  "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-read-word                   "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-temp-buffer                 "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-file-name-absolute          "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-mode-map-activate           "tinydesk" "" nil);;defsubst
(autoload 'tinydesk-add-space-if-non-space      "tinydesk" "" nil)
(autoload 'tinydesk-get-save-dir                "tinydesk" "" nil)
(autoload 'tinydesk-only-files-buffer           "tinydesk" "" t)
(autoload 'tinydesk-only-files-region           "tinydesk" "" t)
(autoload 'tinydesk-trash                       "tinydesk" "" nil)
(autoload 'tinydesk-dired-table                 "tinydesk" "" t)
(autoload 'tinydesk-auto-save-file-name         "tinydesk" "" nil)
(autoload 'tinydesk-auto-save                   "tinydesk" "" t)
(autoload 'tinydesk-face                        "tinydesk" "" nil)
(autoload 'tinydesk-clear-line-properties       "tinydesk" "" nil)
(autoload 'tinydesk-clear-buffer-properties     "tinydesk" "" t)
(autoload 'tinydesk-clear-region-properties     "tinydesk" "" nil)
(autoload 'tinydesk-line-property-set-error     "tinydesk" "" nil)
(autoload 'tinydesk-handle-text-property        "tinydesk" "" nil)
(autoload 'tinydesk-set-face-non-files-region   "tinydesk" "" t)
(autoload 'tinydesk-set-face-non-files-buffer   "tinydesk" "" t)
(autoload 'tinydesk-mark-region                 "tinydesk" "" nil)
(autoload 'tinydesk-mark-buffer-loadable        "tinydesk" "" t)
(autoload 'tinydesk-mouse-load-file             "tinydesk" "" t)
(autoload 'tinydesk-remove-file-coments         "tinydesk" "" t)
(autoload 'tinydesk-expunge-unloaded            "tinydesk" "" t)
(autoload 'tinydesk-unload-current-file         "tinydesk" "" t)
(autoload 'tinydesk-load-file                   "tinydesk" "" t)
(autoload 'tinydesk-unload                      "tinydesk" "" t)
(autoload 'tinydesk-mode                        "tinydesk" "" t)
(autoload 'turn-on-tinydesk-mode                "tinydesk" "" t)
(autoload 'tinydesk-file-p                      "tinydesk" "" nil)
(autoload 'turn-on-tinydesk-mode-maybe          "tinydesk" "" t)
(autoload 'turn-off-tinydesk-mode               "tinydesk" "" t)
(autoload 'tinydesk-edit-state-file             "tinydesk" "" t)
(autoload 'tinydesk-get-save-files              "tinydesk" "" nil)
(autoload 'tinydesk-save-state                  "tinydesk" "" t)
(autoload 'tinydesk-rename-buffer-maybe         "tinydesk" "" t)
(autoload 'tinydesk-find-file                   "tinydesk" "" nil)
(autoload 'tinydesk-recover-state               "tinydesk" "" t)
(autoload 'tinydesk-recover-last-state          "tinydesk" "" nil)
(autoload 'tinydesk-find-file-whole-buffer      "tinydesk" "" t)
(autoload 'tinydesk-recover-file-whole-buffer   "tinydesk" "" t)
(autoload 'tinydesk-install                     "tinydesk" "" t)
(provide 'tinydesk-epkg-autoloads)
